# name: Deployment tests

# on:
#   pull_request:
#     branches:
#       - master

# jobs:
#   cypress-run:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Download the build folders
#         uses: actions/download-artifact@v2
#         with:
#           name: build
#           path: build

#       - name: Cypress run
#         uses: cypress-io/github-action@v2
#         with:
#           build: yarn build
#           start: yarn start
